# Input values for the prover

poll_unit = "12"                # Public poll identifier
private_vote_choice = "1"       # 1 = YES, 2 = NO
private_voter_id = "1"          # Voter ID

[previous_records]
count = "0"                     # No votes yet
poll_units = [
  "0","0","0","0","0","0","0","0","0","0",
  "0","0","0","0","0","0","0","0","0","0",
  "0","0","0","0","0","0","0","0","0","0",
  "0","0","0","0","0","0","0","0","0","0",
  "0","0","0","0","0","0","0","0","0","0",
  "0","0","0","0","0","0","0","0","0","0",
  "0","0","0","0","0","0","0","0","0","0",
  "0","0","0","0","0","0","0","0","0","0",
  "0","0","0","0","0","0","0","0","0","0",
  "0","0","0","0","0","0","0","0","0","0"
]
voter_ids = [
  "0","0","0","0","0","0","0","0","0","0",
  "0","0","0","0","0","0","0","0","0","0",
  "0","0","0","0","0","0","0","0","0","0",
  "0","0","0","0","0","0","0","0","0","0",
  "0","0","0","0","0","0","0","0","0","0",
  "0","0","0","0","0","0","0","0","0","0",
  "0","0","0","0","0","0","0","0","0","0",
  "0","0","0","0","0","0","0","0","0","0",
  "0","0","0","0","0","0","0","0","0","0",
  "0","0","0","0","0","0","0","0","0","0"
]
